# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messeges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=180)),
                ('senton', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
